### ISSUE TITLE
release at least 0.1.0

### ISSUE THREAD

**Issue by MoOx** [cssnext/fly-cssnext#1]
Don't be afraid to follow semver and release 0.1.\* or even better 1.0.0 !
0.0.\* is not cool, especially to provide bugfixes.
Example https://github.com/postcss/postcss-import/blob/master/CHANGELOG.md

**Comment by hzlmn** [comment]
ok, gonna fix.

**Comment by MoOx** [comment]
Could you tag your release as git tag as well?

**Comment by ghost** [comment]
@MoOx :+1: Sure. I've just joined the org too, so I will be taking care of this guy too.

**Comment by hzlmn** [comment]
@MoOx sure

**Comment by MoOx** [comment]
Nice!
