### ISSUE TITLE
handle raw data to string conversion

### ISSUE THREAD

**Issue by ghost** [cssnext/fly-cssnext#2]
Now filters and plugins, will receive the raw data as opposed to a string. This means if the filter/plugin is expecting a string, (for example fly-coffeescript expects the source code to compile as a string) you need to convert the data to a string before you can call any String.prototype methods on it.

See [here](https://github.com/flyjs/fly/releases/tag/v0.6.0)

**Comment by hzlmn** [comment]
@bucaran , i provide You access, so feel free to edit ;) also, i saw your pings and gonna push first version during this day, i think. Sorry..

**Comment by ghost** [comment]
@drKraken Awesome, thank you! :smile:
